### ISSUE TITLE
Consider removing DoublePoint class

### ISSUE THREAD

**Issue by maherou** [maxhelgestad/Pi_Approximator#1]
It's not needed for this simple program.

**Comment by maxhelgestad** [comment]
No longer using DoublePoint or Point in my simulation, rather just calculating the distance from the center, (0.5, 0.5) in my case, with a random x and a random y.

**Comment by maherou** [comment]
Note that the center is (0,0), but the radius is 0.5.  Just making sure this is clear.

**Comment by maxhelgestad** [comment]
I used random values for x and y that ranged from 0 to 1, so in my case the center would be at (0.5, 0.5). Is this acceptable?

**Comment by maherou** [comment]
The new code is correct but confusing. You should compute x and y by subtracting -0.5. Then your darts will land n the board or outside it.

**Comment by maherou** [comment]
You don’t want to subtract it when computing the distance

**Comment by maxhelgestad** [comment]
Ok I understand how this is less confusing. I made this change.
