### ISSUE TITLE
Consider breaking down lines 16 and 17 into simpler expressions

### ISSUE THREAD

**Issue by maherou** [maxhelgestad/Pi_Approximator#2]
These lines are complicated: 

```
 if (Math.sqrt((darts.get(i).getY() - 0.5) * (darts.get(i).getY() - 0.5) + 
  (darts.get(i).getX() - 0.5) * (darts.get(i).getX() - 0.5)) < 0.5){
```

**Comment by maxhelgestad** [comment]
I believe I fixed both issues. I'm no longer using a point class in any way and made the distance calculation much simpler.

**Comment by maxhelgestad** [comment]
This calculation became much simpler when not using a separate Point class, rather just a double "x" value and a double "y" value. Looks much more clean.
